version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672" # Cổng cho giao tiếp AMQP
      - "15672:15672" # Cổng giao diện quản lý
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
#     volumes:
#       - rabbitmq_data:/var/lib/rabbitmq

# volumes:
#   rabbitmq_data:
